wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1677018370.281137
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.7
      5: 0.13.7
      6: 4.26.1
      8:
      - 1
      - 2
      - 5
model_name:
  desc: null
  value: opt-125m
stride:
  desc: null
  value: 2048
token_length:
  desc: null
  value: 2048
